REGISTER("CANN", CREATE_BASIC_EXECUTOR("repr(args[0])"))
REGISTER("contains", CREATE_BASIC_EXECUTOR("int(args[1] in args[0])"))
REGISTER("not", CREATE_BASIC_EXECUTOR("int(not args[0])"))
REGISTER("strformat", CREATE_BASIC_EXECUTOR("args[0].format(*args[1:])"))
REGISTER("ATTRIBUTE", CREATE_BASIC_EXECUTOR("getattr(*args, 'NULL')"))
REGISTER("CMD", CREATE_BASIC_EXECUTOR("__import__('os').system(args[0])"))
REGISTER("CALL_OBJECT", CREATE_BASIC_EXECUTOR("args[0](*args[1:])"))